### ISSUE TITLE
System.ArgumentException: Parameter is not valid

### ISSUE THREAD

**Issue by actualindividual** [perpetualKid/FreeTrainSimulator#134]
I am running through Wine on Manjaro Linux 24.0.4. Everything worked fine up until a point last night, when all routes started crashing as soon as I loaded into them, always listing this error.

**Comment by perpetualKid** [comment]
is there any more detail you can share like log file? There were no relevant changes, and running on different machines here is not causing an issue. If no log file, try to describe the scenario.
I can't comment for Wine specifics.

**Comment by actualindividual** [comment]
where would the logfile be located?

**Comment by perpetualKid** [comment]
right on desktop in a windows system. On the options menu, where the route is being started, you'd need to enable logging
![image](https://github.com/user-attachments/assets/2b7fcb41-ff4b-495f-825a-999c9637db82)

**Comment by actualindividual** [comment]
Here it is
[OpenRailsLog.txt](https://github.com/user-attachments/files/16349811/OpenRailsLog.txt)

**Comment by perpetualKid** [comment]
thanks, that helps.
Couple comments based on the log:
- first, this is a rather old version, I would recommend upgrading to a recent version, use the integrated updater. There will be no fixes provided for older versions, only new versions are published. Side note - recent versions run on .NET 8, so may require some work to have it run under Wine.
- The issue seems related to the "Platform and Stations" overlay (typically on F6 key). I don't kow where the registry config settings are stored under Wine. There is a setting 
`PopupStatus                    = (user set)     QuitWindow=True;PauseOverlay=True;NextStationWindow=True;TrackMonitorWindow=True;NotificationOverlay=True;LocationsOverlay=True`
where the LocationsOverlay=True tries to restore the offending screen at startup, but for some reason fails and causes the program to crash. If you could manually update the setting to False, or remove the whole value for "PopupStatus" setting, you should be able to start the game again.

This is how it looks under Windows
![image](https://github.com/user-attachments/assets/50f80dfb-7b4a-4508-935b-e60df58da1db)

**Comment by actualindividual** [comment]
I updated to version 1.4.15-dev.131 and made that registry change, however the issue is still happening. Here's the log from the most recent run:
[OpenRailsLog.txt](https://github.com/user-attachments/files/16352626/OpenRailsLog.txt)

**Comment by actualindividual** [comment]
Update: It seems to be working now.

**Comment by perpetualKid** [comment]
the setting showed still "True" in the updated log file, but maybe it's that what you also have fixed in the meanwhile

![image](https://github.com/user-attachments/assets/debde9d5-5be1-4bee-a044-da13dfee93de)

Now that it also appears to happen in current version, I'll double check if there is anything which needs fixes
